name: Docker Build & Push to ECR

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/docker-push.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: 447989883825.dkr.ecr.eu-west-2.amazonaws.com
      ECR_REPOSITORY: threat-modeller
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
